name = "JuMPFeasibility"
uuid = "f390cadd-34af-4587-b57d-3913bd0c254b"
authors = ["Thibaut Cuvelier <cuvelier.thibaut@gmail.com>"]
version = "0.1.0"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
